package org.com;
import java.io.File;
import java.io.IOException;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import com.google.common.io.Files;
public class GL {
	public static void main(String[] args) throws IOException, InterruptedException {
		System.setProperty("webdriver.chrome.driver", "C:\\Users\\RAMESH\\eclipse-workspace\\Selenium\\driver\\chromedriver.exe");
		WebDriver driver=new ChromeDriver();
		driver.get("https://adactinhotelapp.com/");
		TakesScreenshot sc=(TakesScreenshot)driver;
		File source=sc.getScreenshotAs(OutputType.FILE);
		File target=new File("C:\\Users\\RAMESH\\OneDrive\\Pictures\\Camera imports\\home.jpg");
		FileUtils.copyFile(source,target);
		WebElement txt=driver.findElement(By.name("username"));
		txt.sendKeys("Joshna2613");
		File tsc=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(tsc, new File("C:\\\\Users\\\\RAMESH\\\\OneDrive\\\\Pictures\\\\Camera imports\\\\username.jpg"));
		WebElement txt1=driver.findElement(By.name("password"));
		txt1.sendKeys("Arvinthanjoshna26");
		File tsc1=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(tsc1, new File("C:\\\\Users\\\\RAMESH\\\\OneDrive\\\\Pictures\\\\Camera imports\\\\password.jpg"));
		WebElement txt2=driver.findElement(By.name("login"));
		txt2.click();
		File tsc2=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(tsc2, new File("C:\\\\Users\\\\RAMESH\\\\OneDrive\\\\Pictures\\\\Camera imports\\\\login.jpg"));
		WebElement location=driver.findElement(By.name("location"));
		Select s=new Select(location);
		s.selectByValue("Sydney");
		WebElement hotel=driver.findElement(By.name("hotels"));
		Select s1=new Select(hotel);
		s1.selectByValue("Hotel Creek");
		WebElement room=driver.findElement(By.name("room_type"));
		Select s2=new Select(room);
		s2.selectByValue("Super Deluxe");
		WebElement roomnos=driver.findElement(By.name("room_nos"));
		Select s3=new Select(roomnos);
		s3.selectByVisibleText("1 - One");
		WebElement adult=driver.findElement(By.name("adult_room"));
		Select s4=new Select(adult);
		s4.selectByVisibleText("2 - Two");
		WebElement child=driver.findElement(By.name("child_room"));
		Select s5=new Select(child);
		s5.selectByVisibleText("0 - None");
		File tsc3=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(tsc3, new File("C:\\\\Users\\\\RAMESH\\\\OneDrive\\\\Pictures\\\\Camera imports\\\\location.jpg"));
		Thread.sleep(2000);
		WebElement txt3=driver.findElement(By.name("Submit"));txt3.click();
		WebElement txt4=driver.findElement(By.name("radiobutton_0"));txt4.click();
		File tsc4=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(tsc4, new File("C:\\\\Users\\\\RAMESH\\\\OneDrive\\\\Pictures\\\\Camera imports\\\\continue.jpg"));
		Thread.sleep(2000);
		WebElement txt5=driver.findElement(By.name("continue"));txt5.click();
		WebElement txt6=driver.findElement(By.name("first_name"));txt6.sendKeys("Arvinthan");
		WebElement txt7=driver.findElement(By.name("last_name"));txt7.sendKeys("Joshna");
		WebElement txt8=driver.findElement(By.name("address"));txt8.sendKeys("Chennai");
		WebElement txt9=driver.findElement(By.name("cc_num"));txt9.sendKeys("8904763174123874");
		WebElement txt10=driver.findElement(By.name("cc_type"));
		Select s6=new Select(txt10);s6.selectByValue("VISA");
		WebElement txt11=driver.findElement(By.name("cc_exp_month"));
		Select s7=new Select(txt11);s7.selectByValue("8");
		WebElement txt12=driver.findElement(By.name("cc_exp_year"));
		Select s8=new Select(txt12);s8.selectByValue("2030");
		WebElement txt13=driver.findElement(By.name("cc_cvv"));txt13.sendKeys("432");
		WebElement txt14=driver.findElement(By.name("book_now"));txt14.click();
		File tsc5=((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);
		Files.copy(tsc5, new File("C:\\\\Users\\\\RAMESH\\\\OneDrive\\\\Pictures\\\\Camera imports\\\\booked"
				+ ".jpg"));
	}
}
